get_filename_component(BASE_CONTROLLER_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(BASE_CONTROLLER_INCLUDE_DIRS "${BASE_CONTROLLER_CMAKE_DIR}/../../../include")
find_library(BASE_CONTROLLER_LIBRARIES base_controller PATHS ${BASE_CONTROLLER_CMAKE_DIR}/../../../lib)
